title: python2-encoded-art
hero_image: images/banner.png
description: design-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Choose a Theme
  - title: Define your shapes
  - title: Place your shapes
  - title: Build your dictionary
  - title: Encode a message
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: Share
  - title: What next?
